// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfEBqyjvWIrIuKrELGB9ezo3lA2g42zeI',
    appId: '1:413210933362:web:408bbd46a5fc41e3086aeb',
    messagingSenderId: '413210933362',
    projectId: 'mad-practice-74780',
    authDomain: 'mad-practice-74780.firebaseapp.com',
    storageBucket: 'mad-practice-74780.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuzfM-iHXE2Rb82GkeYmp15fXHWHKruBQ',
    appId: '1:413210933362:android:d202d5de3d12b5b5086aeb',
    messagingSenderId: '413210933362',
    projectId: 'mad-practice-74780',
    storageBucket: 'mad-practice-74780.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeqET9YhwkZZnKN4tDwRLrdypSDwStg5M',
    appId: '1:413210933362:ios:fb60d0db35b4598e086aeb',
    messagingSenderId: '413210933362',
    projectId: 'mad-practice-74780',
    storageBucket: 'mad-practice-74780.firebasestorage.app',
    iosClientId: '413210933362-eivp9t2p1jip1f81ajvofsqovf9saomr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeqET9YhwkZZnKN4tDwRLrdypSDwStg5M',
    appId: '1:413210933362:ios:fb60d0db35b4598e086aeb',
    messagingSenderId: '413210933362',
    projectId: 'mad-practice-74780',
    storageBucket: 'mad-practice-74780.firebasestorage.app',
    iosClientId: '413210933362-eivp9t2p1jip1f81ajvofsqovf9saomr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfEBqyjvWIrIuKrELGB9ezo3lA2g42zeI',
    appId: '1:413210933362:web:b528f6b722c488ea086aeb',
    messagingSenderId: '413210933362',
    projectId: 'mad-practice-74780',
    authDomain: 'mad-practice-74780.firebaseapp.com',
    storageBucket: 'mad-practice-74780.firebasestorage.app',
  );
}
